<?php

namespace BotMate\Integrations\WordPress\Actions;

use BotMate\Action;

/**
 * User_Register Class
 *
 * @since 1.0
 * @version 1.0
 */
class WP_Insert_User extends Action {

    /**
     * User_Register constructor
     *
     * @param array $args
     * @version 1.0
     * @since 1.0
     */
    public function __construct( $args = array() )
    {
        $args = array(
            'id'            =>  'wp_insert_user',
            'title'         =>  'WordPress Insert User',
            'description'   =>  'Inserts a user into the database.',
            'logo'          =>  BOTMATE_INTEGRATIONS_URL . 'wordpress/assets/logo.png'
        );

        parent::__construct( $args );
    }


    /**
     * Gets the fields for the setup
     *
     * @since 1.0
     * @version 1.0
     */
    public function test_fields() {

        return array(

        );

    }


    /**
     * Registers Trigger
     *
     * @since 1.0
     * @version 1.0
     */
    public function register_action() {

        parent::register_action(); // TODO: Change the autogenerated stub

    }

    /**
     * Action accepting fields
     *
     * @return array 
     * @since 1.0
     * @version 1.0
     */
    public function fields() {

        return array(
            '$user_id'              =>  array(
                'label' =>  'User ID. If supplied, the user will be updated.'
            ),
            '$user_pass'            =>  array(
                'label' =>  'The plain-text user password.'
            ),
            '$user_login'           =>  array(
                'label' =>  'The user\'s login username.'
            ),
            '$user_nicename'        =>  array(
                'label' =>  'The URL-friendly user name.'
            ),
            '$user_url'             =>  array(
                'label' =>  'The user URL.'
            ),
            '$user_email'           =>  array(
                'label' =>  'The user email address.'
            ),
            '$display_name'         =>  array(
                'label' =>  'The user\'s display name. Default is the user\'s username.'
            ),
            '$nickname'             =>  array(
                'label' =>  'The user\'s nickname. Default is the user\'s username.'
            ),
            '$first_name'           =>  array(
                'label' =>  'The user\'s first name. For new users, will be used to build the first part of the user\'s display name if `$display_name` is not specified.' 
            ),
            '$last_name'            =>  array(
                'label' =>  'The user\'s last name. For new users, will be used to build the second part of the user\'s display name if `$display_name` is not specified.'
            ),
            '$description'          =>  array(
                'label' =>  'The user\'s biographical description.'
            ),
            '$rich_editing'         =>  array(
                'label' =>  'Whether to enable the rich-editor for the user. Accepts \'true\' or \'false\' as a string literal, not boolean. Default \'true\'.'
            ),
            '$syntax_highlighting'  =>  array(
                'label' =>  'Whether to enable the rich code editor for the user. Accepts \'true\' or \'false\' as a string literal, not boolean. Default \'true\''
            ),
            '$comment_shortcuts'    =>  array(
                'label' =>  'Whether to enable comment moderation keyboard shortcuts for the user. Accepts \'true\' or \'false\' as a string literal, not boolean. Default \'false\'.'
            ),
            '$admin_color'          =>  array(
                'label' =>  'Admin color scheme for the user. Default \'fresh\'.'
            ),
            '$use_ssl'              =>  array(
                'label' =>  'Whether the user should always access the admin over https. Default false.'
            ),
            '$user_registered'      =>  array(
                'label' =>  'Date the user registered in UTC. Format is \'Y-m-d H:i:s\'.'
            ),
            '$user_activation_key'  =>  array(
                'label' =>  'Password reset key. Default empty.'
            ),
            '$spam'                 =>  array(
                'label' =>  'Multisite only. Whether the user is marked as spam. Default false.'
            ),
            '$show_admin_bar_front' =>  array(
                'label' =>  'Whether to display the Admin Bar for the user on the site\'s front end. Accepts \'true\' or \'false\' as a string literal, not boolean. Default \'true\'.'
            ),
            '$role'                 =>  array(
                'label' =>  'User\'s role.'
            ),
            '$locale'               =>  array(
                'label' =>  'User\'s locale. Default empty.'
            ),
            '$meta_input'           =>  array(
                'label' =>  'Array of custom user meta values keyed by meta key. Default empty.'
            )
        );

    }

}
