<?php

namespace BotMate\Integrations\WordPress\Triggers;

use BotMate\Trigger;

/**
 * User_Register Class
 * 
 * @since 1.0
 * @version 1.0
 */
class User_Register extends Trigger {

    /**
     * User_Register constructor
     *
     * @param array $args
     * @version 1.0
     * @since 1.0
     */
    public function __construct( $args = array() )
    {
        $args = array(
            'id'            =>  'user_register',
            'title'         =>  'User Register',
            'description'   =>  'Fires immediately after a new user is registered.',
            'logo'          =>  BOTMATE_INTEGRATIONS_URL . 'wordpress/assets/logo.png'
        );

        parent::__construct( $args );
    }


    /**
     * Registers Trigger
     *
     * @since 1.0
     * @version 1.0
     */
    public function register_trigger() {

        parent::register_trigger(); // TODO: Change the autogenerated stub

    }

}
